### ISSUE TITLE
Small logic error in handling the 'secure' flag in isCurrentSettingsValid in MqttClient

### ISSUE THREAD

**Issue by slybit** [flespi-software/MQTT-Board#4]
Hi,

I was testing your nice application with my home mqtt server that has no TLS and found that your logic of using the secure flag is wrong in isCurrentSettingsValid in MqttClient. I think it should be like this:

`return this.validateSettings(this.currentSettings) && !(!!this.secure && settings.host.indexOf('ws:') === 0)`

**Comment by scarry1992** [comment]
You are right. My bad. Thanks. Already in master.
